name: Pull request
on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
          
      - name: Git - Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
        
      - name: clean build
        run: |
          xcodebuild clean build -workspace "Application.xcworkspace" -scheme "Application" -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
